### ISSUE TITLE
[ibm-telco] Worker node addition fails with UEFI boot mode

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#84]
This issue is created to add the installation instructions to set boot mode to BIOS.
And also to track support of UEFI boot mode for worker node addition.

**Comment by pmallan** [comment]
@yrobla any update on this? Please update whether UEFI will be supported by ZTP or not

**Comment by pmallan** [comment]
As a workaround, we are using BIOS mode to deploy cluster.

**Comment by yrobla** [comment]
This should be fixed now, please look at https://github.com/redhat-ztp/ztp-cluster-deploy/commit/c6e18536fc4406d70b6b19a68741879f99c54989 , and try using this var in your inventory.

**Comment by pmallan** [comment]
@yrobla we are not able to deploy worker node with stable/4.7 branch. The issue has been reported in #100

**Comment by pmallan** [comment]
The problem still persist.  Tried on Dell servers multiple times but cluster failed with timeout. Let us know if you need log files. Please reopen this issue.

**Comment by yrobla** [comment]
Have you changed the assisted_tag value in your inventory? Can you show me the settings used ?

**Comment by pmallan** [comment]
task Run ztp ansible-playbook tags=add-remote-workers failed: {'msg': 'non-zero return code', 'cmd': 'ansible-playbook playbook.yml -vvv -i inventory/hosts --tags=add-remote-workers', 'stdout': 'ansible-playbook 2.9.20\n config file = /etc/ansible/ansible.cfg\n configured module search path = [\'/root/.ansible/plugins/modules\', \'/usr/share/ansible/plugins/modules\']\n ansible python module location = /usr/lib/python3.6/site-packages/ansible\n executable location = /usr/bin/ansible-playbook\n python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]\nUsing /etc/ansible/ansible.cfg as config file\nhost_list declined parsing /home/ztp/ai-deploy-cluster-remoteworker/inventory/hosts as it did not pass its verify_file() method\nauto declined parsing /home/ztp/ai-deploy-cluster-remoteworker/inventory/hosts as it did not pass its verify_file() method\nParsed /home/ztp/ai-deploy-cluster-remoteworker/inventory/hosts inventory source with ini plugin\nSkipping callback \'actionable\', as we already have a stdout callback.\nSkipping callback \'counter_enabled\', as we already have a stdout callback.\nSkipping callback \'debug\', as we already have a stdout callback.\nSkipping callback \'dense\', as we already have a stdout callback.\nSkipping callback \'dense\', as we already have a stdout callback.\nSkipping callback \'full_skip\', as we already have a stdout callback.\nSkipping callback \'json\', as we already have a stdout callback.\nSkipping callback \'minimal\', as we already have a stdout callback.\nSkipping callback \'null\', as we already have a stdout callback.\nSkipping callback \'oneline\', as we already have a stdout callback.\nSkipping callback \'selective\', as we already have a stdout callback.\nSkipping callback \'skippy\', as we already have a stdout callback.\nSkipping callback \'stderr\', as we already have a stdout callback.\nSkipping callback \'unixy\', as we already have a stdout callback.\nSkipping callback \'yaml\', as we already have a stdout callback.\n\nPLAYBOOK: playbook.yml *********************************************************\n1 plays in playbook.yml\n\nPLAY [Deploy clusters with assisted installer] *********************************\n\nTASK [Gathering Facts] *********************************************************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/playbook.yml:2\n<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root\n<localhost> EXEC /bin/sh -c \'echo ~root && sleep 0\'\n<localhost> EXEC /bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987 `" && echo ansible-tmp-1620660310.3188627-3020757-41532042917987="` echo /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987 `" ) && sleep 0\'\n<localhost> Attempting python interpreter discovery\n<localhost> EXEC /bin/sh -c \'echo PLATFORM; uname; echo FOUND; command -v \'"\'"\'/usr/bin/python\'"\'"\'; command -v \'"\'"\'python3.7\'"\'"\'; command -v \'"\'"\'python3.6\'"\'"\'; command -v \'"\'"\'python3.5\'"\'"\'; command -v \'"\'"\'python2.7\'"\'"\'; command -v \'"\'"\'python2.6\'"\'"\'; command -v \'"\'"\'/usr/libexec/platform-python\'"\'"\'; command -v \'"\'"\'/usr/bin/python3\'"\'"\'; command -v \'"\'"\'python\'"\'"\'; echo ENDFOUND && sleep 0\'\n<localhost> EXEC /bin/sh -c \'/usr/bin/python3.6 && sleep 0\'\nUsing module file /usr/lib/python3.6/site-packages/ansible/modules/system/setup.py\n<localhost> PUT /root/.ansible/tmp/ansible-local-3020728y4hav_gc/tmpw48aqhab TO /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987/AnsiballZ_setup.py\n<localhost> EXEC /bin/sh -c \'chmod u+x /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987/ /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987/AnsiballZ_setup.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987/AnsiballZ_setup.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'rm -f -r /root/.ansible/tmp/ansible-tmp-1620660310.3188627-3020757-41532042917987/ > /dev/null 2>&1 && sleep 0\'\nok: [localhost]\nMETA: ran handlers\n\nTASK [add-remote-workers : Enroll remote worker if needed] *********************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/main.yml:2\nincluded: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml for localhost\nincluded: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml for localhost\n\nTASK [add-remote-workers : Check if the node is already enrolled] **************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:1\n<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root\n<localhost> EXEC /bin/sh -c \'echo ~root && sleep 0\'\n<localhost> EXEC /bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999 `" && echo ansible-tmp-1620660311.5989096-3020915-9114556959999="` echo /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999 `" ) && sleep 0\'\nUsing module file /usr/lib/python3.6/site-packages/ansible/modules/commands/command.py\n<localhost> PUT /root/.ansible/tmp/ansible-local-3020728y4hav_gc/tmpgb396rqb TO /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999/AnsiballZ_command.py\n<localhost> EXEC /bin/sh -c \'chmod u+x /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999/ /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999/AnsiballZ_command.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'PATH=/usr/bin/:/usr/local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin AI_URL=http://9.42.98.148:8080 /usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999/AnsiballZ_command.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'rm -f -r /root/.ansible/tmp/ansible-tmp-1620660311.5989096-3020915-9114556959999/ > /dev/null 2>&1 && sleep 0\'\nchanged: [localhost] => {\n "changed": true,\n "cmd": "aicli list hosts | grep woker-node-1 | wc -l",\n "delta": "0:00:00.263368",\n "end": "2021-05-10 11:25:12.091086",\n "invocation": {\n "module_args": {\n "_raw_params": "aicli list hosts | grep woker-node-1 | wc -l",\n "_uses_shell": true,\n "argv": null,\n "chdir": null,\n "creates": null,\n "executable": null,\n "removes": null,\n "stdin": null,\n "stdin_add_newline": true,\n "strip_empty_ends": true,\n "warn": true\n }\n },\n "rc": 0,\n "start": "2021-05-10 11:25:11.827718",\n "stderr": "",\n "stderr_lines": [],\n "stdout": "1",\n "stdout_lines": [\n "1"\n ]\n}\n\nTASK [Enroll a SuperMicro node] ************************************************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:7\nskipping: [localhost] => {\n "changed": false,\n "skip_reason": "Conditional result was False"\n}\n\nTASK [Enroll a Dell node] ******************************************************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:19\nskipping: [localhost] => {\n "changed": false,\n "skip_reason": "Conditional result was False"\n}\n\nTASK [add-remote-workers : Check if the node is already enrolled] **************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:1\n<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root\n<localhost> EXEC /bin/sh -c \'echo ~root && sleep 0\'\n<localhost> EXEC /bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796 `" && echo ansible-tmp-1620660312.262782-3020957-10493460033796="` echo /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796 `" ) && sleep 0\'\nUsing module file /usr/lib/python3.6/site-packages/ansible/modules/commands/command.py\n<localhost> PUT /root/.ansible/tmp/ansible-local-3020728y4hav_gc/tmpjnzjdl8_ TO /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796/AnsiballZ_command.py\n<localhost> EXEC /bin/sh -c \'chmod u+x /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796/ /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796/AnsiballZ_command.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'PATH=/usr/bin/:/usr/local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin AI_URL=http://9.42.98.148:8080 /usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796/AnsiballZ_command.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'rm -f -r /root/.ansible/tmp/ansible-tmp-1620660312.262782-3020957-10493460033796/ > /dev/null 2>&1 && sleep 0\'\nchanged: [localhost] => {\n "changed": true,\n "cmd": "aicli list hosts | grep woker-node-2 | wc -l",\n "delta": "0:00:00.251978",\n "end": "2021-05-10 11:25:12.661949",\n "invocation": {\n "module_args": {\n "_raw_params": "aicli list hosts | grep woker-node-2 | wc -l",\n "_uses_shell": true,\n "argv": null,\n "chdir": null,\n "creates": null,\n "executable": null,\n "removes": null,\n "stdin": null,\n "stdin_add_newline": true,\n "strip_empty_ends": true,\n "warn": true\n }\n },\n "rc": 0,\n "start": "2021-05-10 11:25:12.409971",\n "stderr": "",\n "stderr_lines": [],\n "stdout": "0",\n "stdout_lines": [\n "0"\n ]\n}\n\nTASK [Enroll a SuperMicro node] ************************************************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:7\nskipping: [localhost] => {\n "changed": false,\n "skip_reason": "Conditional result was False"\n}\n\nTASK [Enroll a Dell node] ******************************************************\ntask path: /home/ztp/ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/add_remote_worker.yaml:19\n\nTASK [/home/ztp/ai-deploy-cluster-remoteworker/../common-roles/enroll-dell : Copy template racadm] ***\ntask path: /home/ztp/common-roles/enroll-dell/tasks/main.yml:1\n<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root\n<localhost> EXEC /bin/sh -c \'echo ~root && sleep 0\'\n<localhost> EXEC /bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1620660312.8528874-3020999-23995524721974 `" && echo ansible-tmp-1620660312.8528874-3020999-23995524721974="` echo /root/.ansible/tmp/ansible-tmp-1620660312.8528874-3020999-23995524721974 `" ) && sleep 0\'\nUsing module file /usr/lib/python3.6/site-packages/ansible/modules/files/stat.py\n<localhost> PUT /root/.ansible/tmp/ansible-local-3020728y4hav_gc/tmpo99nfbmw TO /root/.ansible/tmp/ansible-tmp-1620660312.8528874-3020999-23995524721974/AnsiballZ_stat.py\n<localhost> EXEC /bin/sh -c \'chmod u+x /root/.ansible/tmp/ansible-tmp-1620660312.8528874-3020999-23995524721974/ /root/.ansible/tmp/ansible-tmp-1620660312.8528874-3020999-23995524721974/AnsiballZ_stat.py && sleep 0\'\n<localhost> EXEC /bin/sh -c \'PATH=/usr/bin/:/usr/local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin /usr/libexec/platform-python /root/.ansible/tmp/a...

**Comment by pmallan** [comment]
[root@ztpautoqa ~]# cat /home/ztp/ai-deploy-cluster-remoteworker/inventory/hosts
[all:vars]pull_secret={"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==","email":"pmallana@in.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==","email":"pmallana@in.ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==","email":"pmallana@in.ibm.com"},"registry.redhat.iopmallana@in.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==","email":"pmallana@in.ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==","email":"pmallana@in.ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==","email":"pmallana@in.ibm.com"}}}ssh_public_key=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/JeWL9Y2xzGhOk8IoXoubPB/OeBhVTWpSumPiUmIlJVBYnS43hG2DJ089QI8Da/lFpmXU7G+3sk1vddMVh+jKxp1lzO9wQgsErUSh6udXUKO9vko8uNsW4lETtgpsSjCFJTbEcDTI990HoFw1eaZQpVf9Vd1ohjw77jEwQ1XoX3WuJii1YPuWxccobkixJr1S2h1GNPe9LeQNyXGBW0x+cl4l4OwVq8p5bHr+eWwLCTjljCgo1DslWi+qD7gRCEJbImp+75I+vWEGXOZCm9F7MLWRdwamNTaJma1nai3iCU3g/L/IXox9wx4/qPvgvRFO4b4ry1Lmo0rp6Y1ARDirxNHFHRUbl3kOplP+cy9ugxajJ1KB0ZUGXAnUSmndbr4HeZkzrudIfMlsvjsfxbTdt7jWEKcyHJBERcSvlJLy/FyxYoByxpj0D2g5Znah2WXelMaqkw1I2nkAZ1oa5vS7s4szj7eXOdaoAVKbnIxtUI6Mm25vawbzfQwBuv9qgbc= root@vcuhost.rtp.raleigh.ibm.comai_url="http://9.42.98.148:8080"
iso_url="http://9.42.98.148"ai_version=ac59176add3f1a5f89fe47e1df021d9c9ab7589c
assisted_tag=v1.0.18.3cluster_name=ocpclusterkiran
cluster_domain=rtp.raleigh.ibm.com
cluster_version=4.6
cluster_sdn=OpenShiftSDNingress_vip=9.42.98.171
api_vip=9.42.98.151bridge_name=ztp-br
libvirt_uri="qemu:///system"
need_racadm=Truetemporary_path=/tmpfinal_iso_path=/var/www/html#libvirt_images_path#network_config_pathhaproxy_http_port=8008haproxy_https_port=8443[provisioner]
localhost ansible_connection=local[master_nodes]
master-node1 name=master-node1 mac_address=52:54:00:55:f3:11
master-node2 name=master-node2 mac_address=52:54:00:55:f3:12
master-node3 name=master-node3 mac_address=52:54:00:55:f3:13[worker_nodes]
woker-node-1 name=woker-node-1 bmc_type=Dell bmc_address=9.42.98.136 bmc_user=root bmc_password=3KWAAMK9W3PN redeploy=false
woker-node-2 name=woker-node-2 bmc_type=Dell bmc_address=9.42.98.135 bmc_user=root bmc_password=YVA4XAVVFFE9 redeploy=false
[root@ztpautoqa ~]#

9:48

{
    "master_host_ip": "9.42.98.148",
    "acm_hub_server": "api.vrandev20.cp.fyre.ibm.com:6443",
    "acm_hub_user": "kubeadmin",
    "acm_hub_password": "f7H25-VLX3g-aVcW6-mCDjh",
    "acm_manifest_repo": "https://github.com/redhat-ztp/ztp-acm-manifests",
    "ai_port": 8080,
    "ai_version": "ac59176add3f1a5f89fe47e1df021d9c9ab7589c",
    "api_vip": "9.42.98.151",
    "assisted_tag": "v1.0.18.3",
    "bridge_name": "ztp-br",
    "cluster_domain": "rtp.raleigh.ibm.com",
    "cluster_port": 6443,
    "cluster_sdn": "OpenShiftSDN",
    "cluster_version": 4.6,
    "domain_name": "rtp.raleigh.ibm.com",
    "final_iso_path": "/var/www/html",
    "hw": "dell",
    "ingress_vip": "9.42.98.171",
    "master_host_name": "ztpautoqa",
    "need_racadm": true,
    "profile": "cu",
    "pull_secret": "{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==\",\"email\":\"pmallana@in.ibm.com\"},\"quay.io\":{\"auth\":\"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==\",\"email\":\"pmallana@in.ibm.com\"},\"registry.connect.redhat.com\":{\"auth\":\"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==\",\"email\":\"pmallana@in.ibm.com\"},\"registry.redhat.iopmallana@in.ibm.com\"},\"quay.io\":{\"auth\":\"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZGI1MmY0MzQ4NTIzNDg5MTk2MWM2MjZlMjNmYTU2NDY6UjhHVVBJTTdJQ0ZXTFpZMk1GVEQ0TEMyQ0tLVVAwREFZMUNVWDRHQTdMOEkzWU9PREw3SFhDOUM1U01OOFhZQg==\",\"email\":\"pmallana@in.ibm.com\"},\"registry.connect.redhat.com\":{\"auth\":\"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==\",\"email\":\"pmallana@in.ibm.com\"},\"registry.redhat.io\":{\"auth\":\"fHVoYy1wb29sLTljZDYwYzYzLTVlMDgtNDg1Ni1hZWQwLTlkNzBhNGYxZjU4MzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPR1UyT0RZeU16UTVPVFEwTmpkaVlUSTVaakV3TmpVek5XSTFOemxsWmlKOS5xZnVJenZFaC1vMHZQMC1UMFhuaUUxYmpVeU1uN1EtZmxDNnpBUmhsZGpfTjc2MXRrVm8tZ0E1clNZdHJoNUhPUzVHOXRsVHRIWE5SYVVWcEk2STJpRDNXUkFmckdwUUJnVTdWWVE1OFJ4dFczdDVaRElwRC1GcjhFTFdEZDV0ZjJxdXlvMlFLVDVJdFc0Ym40dE9jdmRLUEZsdmFVUkxBdS05c0Z3LUN0UW84SG80YW5MTmZhY0tRTVRzMktYX0lrSUtNeDl4MFVDT0xCc1MtRk1yYlpHWEtCVlpraV94LU1fTVVUd0lpVXVDd1MtRHlJSlJSVURCdTE1bkF4SDM2VWFEdmpCUFhlUXdlejU3V3diVmZlcVRkcDNfM2FFUEpkZ2dQUUFJVmJ4R091OU50VkpUM0F6ZUVyQTZ0d2V2TnEzdk9CUElLTWYyaFJsd0ZpTkt4YmNoTXZJcXlQSXdMMjd5dDd0UlUzdG81RDRPSXF6TjlKQllvd2RsT1NxS284d042QkpPaFh5S1FrNHVjWUJuWWM5dlZaS0lCRzRaSU1Lb29DVXJRMmctS01PNDM5Z1FOSDF4R3JLQ25zdWZsYzc2b2xobFZPcUFRYUxwUkFuMThzcWw3N211RFNPNGhCS0ZHYzhQZVNJOWRzN3Fxd2dsWW9GLVVLSmc5SWEtVHJJSXpXQ3BzRFRxaDAtdk1rQXFFNVlvQlhmQ25oZHFfYWdvUk8tRlMxaVlBZE5sQUlzMHNSMXNEdUxBVWJNZkpFaHc4N1l1MWVocVlwcXVURVNLbUtMR0FnZG5mYWpFczlPbGszNTlmdGwzX192Y3hiTXpRMFItdU5BVjZSWkZjODNQRkFWeW0xeTRfbWNQc2dQWkhEMlMtWFBHWDdobklmanJaNW9oTVNzSQ==\",\"email\":\"pmallana@in.ibm.com\"}}}",
    "ssh_public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/JeWL9Y2xzGhOk8IoXoubPB/OeBhVTWpSumPiUmIlJVBYnS43hG2DJ089QI8Da/lFpmXU7G+3sk1vddMVh+jKxp1lzO9wQgsErUSh6udXUKO9vko8uNsW4lETtgpsSjCFJTbEcDTI990HoFw1eaZQpVf9Vd1ohjw77jEwQ1XoX3WuJii1YPuWxccobkixJr1S2h1GNPe9LeQNyXGBW0x+cl4l4OwVq8p5bHr+eWwLCTjljCgo1DslWi+qD7gRCEJbImp+75I+vWEGXOZCm9F7MLWRdwamNTaJma1nai3iCU3g/L/IXox9wx4/qPvgvRFO4b4ry1Lmo0rp6Y1ARDirxNHFHRUbl3kOplP+cy9ugxajJ1KB0ZUGXAnUSmndbr4HeZkzrudIfMlsvjsfxbTdt7jWEKcyHJBERcSvlJLy/FyxYoByxpj0D2g5Znah2WXelMaqkw1I2nkAZ1oa5vS7s4szj7eXOdaoAVKbnIxtUI6Mm25vawbzfQwBuv9qgbc= root@vcuhost.rtp.raleigh.ibm.com"
}

**Comment by yrobla** [comment]
Please, can try adding ai_version=9d91b6559d5ffa40ae354cb1fa2070a808a2da5e as well?
Also please do not add private pull secrets like the one of your inventory in a public issue... this can be taken by anyone and use your credentials to access those sites. I will remove the comments in this issue as a security measure.

**Comment by pmallan** [comment]
@yrobla we tried with this adding ai_version=9d91b6559d5ffa40ae354cb1fa2070a808a2da5e parameter. It did not help. Node fails to reboot when it is UEFI boot mode however works with BIOS boot mode. Did you try this in your test environment?. If so please share details of DELL server you tried. Do let me know if you need any logs

**Comment by yrobla** [comment]
What do you mean with "fails to reboot" ? have you reached further than with previous tries?
We tested that with Dell-R640 and worked fine.
Would be useful if you can send logs, and/or attach a video of the sever when tried to be provisioned with that method.

**Comment by pmallan** [comment]
BOOT mode: UEFI problem, I tried on new lab dell servers but still getting the same issue `PXE: No media detected.` (tried manually)
- Configurations -> BIOS Settings -> BIOS Settings -> BOOT mode -> UEFI
- Virtual Media -> Remote File Share -> Image File Path -> http://172.29.231.89/sos-cluster-qa-day2.iso and connected successfully.
- Boot -> Virtual CD/DVD/ISO
- Power -> Reset System (warm boot)
- Tried shutdown and power on but still same issue observed
Same dell servers works fine with BOOT mode: BIOS
PFA video capture for the same.

https://user-images.githubusercontent.com/79190301/118292590-6be42380-b4f6-11eb-98e9-bc0a64c88cc2.mp4

**Comment by pmallan** [comment]
@yrobla it is bit strange issue. Let us know if we need to raise this issue with hw vendor

**Comment by yrobla** [comment]
Looks like the ISO is not yet correct, but shouldn't be the case if you are consuming latest commit and latest base image. Can you send me a copy of your inventory, and if it's possible, a copy of the generated iso (share it on google drive or any other file sharing)

**Comment by pmallan** [comment]
@yrobla  ISO is there in google drive https://drive.google.com/drive/folders/1CZy3sceMmqjD8HvFD3xqK-YcX_c3Uc7G. It is there in google drive. Need to know your gmail id to share with you.

**Comment by yrobla** [comment]
So what's the base image you are using, 4.6? We found issues witih 4.6 booting with uefi, even with latest code. Can you try 4.7 or 4.8 images? It may be the case that you need to stick with bios for 4.6

**Comment by pmallan** [comment]
We are trying with 4.6 base images since our development environment is 4.6. Not tried with 4.7 or 4.8 images as we have not planned to move to 4.7 yet.
